### ISSUE TITLE
Favioli branding

### ISSUE THREAD

**Issue by ivebencrazy** [ivebencrazy/favioli#19]
We need some favicons, icons, banners, etc for Chrome Store.

- [x] Icons (https://github.com/ivebencrazy/favioli/pull/25/commits/caf94f7b7755038a4a575f0f3fe4a9333a26ba13)
- [x] Chrome Store Banners (won't fix)
- [x] Landing Page Website (https://www.favioli.com)
- [x] Update READMEs (https://github.com/ivebencrazy/favioli/blob/master/README.md)
- [x] Blog Post (https://www.benpevsner.com/post/favioli)

**Comment by eligrey** [comment]
Here's a comparison graphic:

![favioli-comparison](https://user-images.githubusercontent.com/46995/43301322-48332cb4-9119-11e8-93e4-851954a52560.png)
