### ISSUE TITLE
Emoji favicon present for inbox.google.com

### ISSUE THREAD

**Issue by jameshiew** [ivebencrazy/favioli#30]
An emoji favicon is added for https://inbox.google.com even though the site already has a favicon set.

![screen shot 2018-08-20 at 22 08 31](https://user-images.githubusercontent.com/2990876/44366765-b0693e80-a4c5-11e8-94d0-23a66dafa008.png)

Refreshing the page changed it back to the normal Inbox favicon.

**Comment by ivebencrazy** [comment]
o yup I see this; lemme investigate.  Thanks for the tip!

**Comment by ivebencrazy** [comment]
I think this PR will fix your issue.  Does the steps described in there look like it could be what was wrong?

**Comment by jameshiew** [comment]
Yes from what you described in your PR that sounds like it was the cause of the issue. Thank you for making and maintaining this plugin! 🎉
