### ISSUE TITLE
Favicon override on Firefox

### ISSUE THREAD

**Issue by xuhcc** [ivebencrazy/favioli#47]
**Describe the bug**

Favicon is replaced by emoji on some sites.

**To Reproduce**

Go to https://pythonhosted.org/PyInstaller/usage.html

**Expected behavior**

Existing favicon should be preserved.

**Screenshots**

With Favioli:

![screenshot from 2018-11-03 14-06-16](https://user-images.githubusercontent.com/1660460/47951475-50395300-df72-11e8-81db-ae1ac0095094.png)

Without Favioli:

![screenshot from 2018-11-03 14-08-49](https://user-images.githubusercontent.com/1660460/47951480-59c2bb00-df72-11e8-94aa-5237da355b65.png)

**Desktop:**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 63

**Comment by ivebencrazy** [comment]
Thanks for the bug!  I saw this myself the other day as well, and I think I have an idea how to fix.
https://github.com/ivebencrazy/favioli/pull/46

Will try and get a patch out in the next day or so.

**Comment by ivebencrazy** [comment]
Pushed patch #46 a minute or so ago; looks like it's live now.  Looks like it's working for me now.  Let me know if you don't see this fixed when your Favioli is updated 👍 

Thanks for using Favioli, and for pinging me about this issue!

<img width="334" alt="screen shot 2018-11-03 at 9 46 45 am" src="https://user-images.githubusercontent.com/8182843/47954909-81535c80-df4d-11e8-97f1-b656cc32eb08.png">

**Comment by xuhcc** [comment]
Problem is gone, thank you!
