### ISSUE TITLE
Overrides not working :(

### ISSUE THREAD

**Issue by Gitoffthelawn** [ivebencrazy/favioli#50]
Overrides are not working.  :cry: 

Tested in Firefox 75.

**Comment by ivebencrazy** [comment]
Hihi are you using Windows?  That feature is working for me, but I also got a bad review somewhat recently about FF on Windows.  I'd been putting it off, since I don't have a windows machine, but maybe I'll just break down and get parallels.

**Comment by Gitoffthelawn** [comment]
Yes, I tested on a Windows box.  I'm trying to think what would make the issue OS-dependent.

I just took a look at the reviews.  It sounds like the same issue is the same as the second 1 star review.  Too bad they didn't post it here.  I'm not sure if the 4 star review is also the same issue.  Then there is the 3 star review that doesn't make sense to me.

**Comment by ivebencrazy** [comment]
For sure!  Thanks for making an issue, and putting in this extra effort to give me more information!  I'll try and debug later today.

**Comment by Gitoffthelawn** [comment]
You're welcome!  And that *you*!

BTW, it's a bit out of scope, but I would love to have a tool that reloads/resets the favicon for any Firefox bookmark.

Right now, I have to delete the bookmark, vacuum the `places` and `favicon` SQLite databases, close Firefox, re-open Firefox, and recreate the bookmark.  That's a lot of work to update a favicon!  :-)

**Comment by ivebencrazy** [comment]
^ looks like this fixes it.  I want to run through and manually test it a bit so I can make sure I don't break anything for other users, so you can expect it to be released probably by tomorrow, assuming everything continues to work as expected.

> Reloads/Resets favicon for any FF bookmark?

You mean more as a general utility, rather than related to emojis, correct?

I'm not against adding a utility like this to the options menu later.  I'm a bit overloaded by other commitments at the moment, so I'm not really looking to add features to this until after summer this year.  If you want it faster, and don't mind playing around in the code, I'd welcome a PR.  😅  Though I'd imagine you'd want this in a browser popup menu, which doesn't exist in Favioli atm.

**Comment by Gitoffthelawn** [comment]
> looks like this fixes it. I want to run through and manually test it a bit so I can make sure I don't break anything for other users, so you can expect it to be released probably by tomorrow, assuming everything continues to work as expected.

Wow!  Thank you so much! :smile: 

>>    Reloads/Resets favicon for any FF bookmark?

> You mean more as a general utility, rather than related to emojis, correct?

Yes.  It could definitely be a small separate extension.  I figured I had a better chance of it happening if I suckered you into including it into this extension. :smile: :smile: :smile: 

> I'm not against adding a utility like this to the options menu later. I'm a bit overloaded by other commitments at the moment, so I'm not really looking to add features to this until after summer this year. If you want it faster, and don't mind playing around in the code, I'd welcome a PR. sweat_smile 

I've been trying to figure out favicon stuff in Firefox, and I'm sure how this would be accomplished.  That's why I decided to mention it to you, since you have successful experience with it already.

There's another extension that sort of does this, https://github.com/tanwald/checkmarks , but it works on entire folders.  And I haven't determined yet if it actually fixes favicons when Firefox gets confused.

> Though I'd imagine you'd want this in a browser popup menu, which doesn't exist in Favioli atm.

I was actually just thinking of a context menuitem for the bookmark that would reload the a site's default favicon for any bookmark that is missing one.  It actually would be good functionality for Favioli, because if you assign a Favioli favicon to a bookmark, I don't think there is currently a way to go back to the site's default favicon.

**Comment by ivebencrazy** [comment]
Ahhh okok.  I’ve been meaning to integrate bookmarks stuff in the future, so this lines up with my expected timeline (only thing I have prioritized before bookmark support is more granular permissions).  

But, yeah, probably won’t get after that stuff for at least a few months, so you’ll have to be a bit patient with me.

**Comment by Gitoffthelawn** [comment]
No problem.  If you will, add a comment to this issue when you work on it so it comes up on my radar.

**Comment by Gitoffthelawn** [comment]
Oh wait, scratch that.  I'll add a new issue.
