### ISSUE TITLE
Whitelist Specific Websites

### ISSUE THREAD

**Issue by PHJDvzdmS7hQlN9J6O1** [ivebencrazy/favioli#53]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem.
While Favioli is active, the _login_ Fastmail page breaks.
_As soon as I disable Favioli_, the _login_ Fastmail website works.

**Describe the solution you'd like**
Be able to whitelist a website bypassing the existing Favioli overrides, i.e. render the overrides useless purposelessly for a determined website. 

**Describe alternatives you've considered**
1. To bypass the Favioli issue with Fastmail, I log to my Fastmail account using the Chrome browser incognito mode.
2. I opened a ticket with Fastmail. Their web engineers are still working on it. No solution from them yet.
3. I emailed Google requesting the addition of an ON/OFF radio button in the Chrome toolbar extensions icon drop-down menu for each installed extension. It would allow for the rapid enabling/disabling of Favioli with one click.

**Additional context**
I use only one Favioli override, i.e. asterisk.asterisk and the same favicon for all overrides: a small black square.
I use Favioli for privacy reasons rather than aesthetic.
By using Favioli, I prevent favicon diversity and feed trackers the same favicon always. Therefore, they're unable to track my web path due to the similitude of favicons in local storage: no favicon variety, no path distinction.

[Schneier on Security](https://www.schneier.com/blog/archives/2021/02/browser-tracking-using-favicons.html)

I believe that Favioli might have issues with scalable vector graphics favicons.
By overriding the Fastmail SVG favicon the embedded scripting part could be affected resulting in the page not loading.

**Comment by ivebencrazy** [comment]
ooo Thank you for making an issue!  Sorry I haven't been paying attention to my github notifications.... 😅
This is a very interesting usecase that I did not expect.  And an interesting bug as well!

Adding a list of bypass sites is a very reasonable idea.  I'm not spending a lot of time on personal code projects currently, but this should be a relatively straightforward patch.  So the solution will likely not be incredibly elegant, but I should be able to push you something this week.

**Comment by ivebencrazy** [comment]
v1.3.0 is now released for Firefox, under review for Chrome.
